PhoneResponsive={"785":{
"pageLayer":{"w":785,"h":450,"bgColor":"#ffffff"}
,
"text665":{"x":57,"y":82,"w":671,"h":18,"txtscale":100,"bOffBottom":0}
,
"entry666":{"x":57,"y":101,"w":160,"h":25,"fsize":16,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"480":{
"pageLayer":{"w":480,"h":763,"bgColor":"#ffffff"}
,
"text665":{"x":35,"y":50,"w":410,"h":37,"txtscale":100,"bOffBottom":0}
,
"entry666":{"x":35,"y":101,"w":160,"h":25,"fsize":16,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
